-- AlterTable
ALTER TABLE `User`
  MODIFY `role` ENUM('GOD', 'ADMIN', 'OWNER', 'PICKER') NOT NULL DEFAULT 'PICKER';

ALTER TABLE `Membership`
  MODIFY `role` ENUM('GOD', 'ADMIN', 'OWNER', 'PICKER') NOT NULL DEFAULT 'PICKER';

ALTER TABLE `InviteCode`
  MODIFY `role` ENUM('GOD', 'ADMIN', 'OWNER', 'PICKER') NOT NULL;
